# Site settings
myname: Stefano Chittaro
title: KitOps
email: 4a88a517a3b3e932904036de36f53d79
url: www.kitops.eu
description: "Helping teams simplify the complex with Kubernetes, cloud automation, and smart system design."
keywords: "devops, security, linux, Kubernetes"
skills: "DevSecOps & Platform Engineer"
certifications: "Certified Kubernetes Administrator & Security Specialist"
meta_author: Stefano Chittaro

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 037dba
  primary-rgb: "3,125,186" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: No rights reserved
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stefano-chittaro/
  - title: github
    url: https://github.com/nevarsin

# Postal address (add as many lines as necessary)
address:
  - line: Udine
  - line: Italy

# Credits content
credits: 'Theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

host: 0.0.0.0